### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by mikera** [eprunier/cerebro#1]
Hi Eric,

Great that you are doing linear algebra / machine learning work in Clojure!

Saw that you are using `core.matrix` and `EJML` which is cool - was hoping to see someone try this out at some point.

Just wanted to alert you that I'm doing something similar as part of vectorz-clj (https://github.com/mikera/vectorz-clj) - in particularly I'm working on a port of the linear algebra stuff from EJML to vectorz - see this branch https://github.com/mikera/vectorz/tree/ejml-import

I'm doing this because the EJML linear algebra algorithms are awesome, but IMHO Vectorz is better for actual vector maths and the flexibility of the vector / matrix representations (specialised matrices and views etc.). I wanted to get the best of both worlds :-)

Anyway -  if you want to collaborate on any of this stuff then the door is always open!

  Mike.

**Comment by eprunier** [comment]
Hi Mike,

I'm currently studying linear algebra and machine learning on my spare time.
I have choosen EJML for it's great documentation (and especially for the
"Matlab to EJML" tutorial) which is quite comprehensible for a newbie like
me.

The creation of an implementation of matrix-api over EJML is a way for me
to dive into core.matrix and then explore others wrappers like Clatrix.
I must admit that Vectorz is a bit intimidating for me but I hope to become
more confident with it in the future.

I would like to thank you for your great work on Clojure Numerics which is
a source of inspiration.

Eric

Eric Prunier
about.me/ericprunier

2013/7/18 Mike Anderson notifications@github.com

**Comment by mikera** [comment]
OK, no problem!

It will be certainly great to have an EJML implementation for `core.matrix`, so good luck with it!
